[package]
name = "eywa-hateoas"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
thiserror = { workspace = true }
eywa-pagination = { path = "../eywa-pagination" }
eywa-errors = { workspace = true }